# ===========================================================================
# VERIFICATION & JOIN ROLES CONFIGURATION
# ===========================================================================
JoinRoleSettings:
  Enabled: false
  JoinRoles: ["ROLE_ID", "ROLE_ID"] # Roles users get immediately when they join your server
  RestoreRoles: # Should the user get back their original roles before leaving the server?
    Enabled: false # Leave below blank to give all roles
    Blacklist: ["ROLE_ID", "ROLE_ID"] # If used, any roles not in the whitelist won't be given
    Whitelist: ["ROLE_ID", "ROLE_ID"] # If used, all roles will be given apart from the ones defined

# Verification Types:
# BUTTON - When a user clicks the button, they get the specified role
# CALCULATOR - Solve a math question to get a specified role
VerificationSettings:
  Enabled: false # Enable users to verify when they join your discord server?
  DeleteAllMessages: false # Delete all user messages in the verification channel?
  ChannelID: ["CHANNEL_ID"] # Supports multiple channel IDs for different guilds
  VerificationType: BUTTON # Options: BUTTON, CALCULATOR, CAPTCHA
  VerifiedRoleID: ["ROLE_ID"] # Supports multiple role IDs for different guilds
  RoleToRemove: [""] # Supports multiple role IDs for different guilds. Leave blank for none.
  EnableUnverifiedRole: false # Enable the Unverified role? (Automatically created and denied access to all channels other than verify channel)

VerificationEmbed:
  Title: "Verify"
  Description: "Please verify to get full access to the server.\nClick the **button** below to get verified!"
  Image: "https://i.imgur.com/R4qVpUy.png"

VerificationButton:
  Name: "Verify"
  Emoji: "âœ…"
  Color: Secondary # Primary, Secondary, Success, Danger